services:
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379

  db:
    image: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./usr:/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - "db"

  test-db:
    image: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  dbdata:
  data:
